name: DPP-Core
version: 5.0.4.46
description: All DP-PLUGINS plugins require this plugin.
main: com.darksoldier1404.dppc.DPPCore
authors: [ DEAD_POOLIO_ ]
api-version: 1.14
softdepend:
  - Essentials
  - PlaceholderAPI
  - ProtocolLib
  - LuckPerms
  - WorldGuard
  - Vault
commands:
  dppc:
  dppca:
  dppcp: